### ISSUE TITLE
mysqltcl3.05 does not compile with MySQL 8.0 dev library

### ISSUE THREAD

**Issue by fayce66** [xdobry/mysqltcl#3]
The my_bool type is no longer used in MySQL 8.0+ source code. Any third-party code that used this type to represent C boolean variables should use the bool or int C type instead. (cf https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-1.html#mysqld-8-0-1-compiling)

gcc -pipe -DPACKAGE_NAME=\"mysqltcl\" -DPACKAGE_TARNAME=\"mysqltcl\" -DPACKAGE_VERSION=\"3.052\" -DPACKAGE_STRING=\"mysqltcl\ 3.052\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIMITS_H=1 -DHAVE_SYS_PARAM_H=1 -DUSE_THREAD_ALLOC=1 -D_REENTRANT=1 -D_THREAD_SAFE=1 -DTCL_THREADS=1 -D_LARGEFILE64_SOURCE=1 -DTCL_WIDE_INT_IS_LONG=1 -DUSE_TCL_STUBS=1  -I"/usr/include" -I/usr/include/mysql    -O2 -fomit-frame-pointer -Wall -Wno-implicit-int -fPIC -c `echo ./generic/mysqltcl.c` -o mysqltcl.o
./generic/mysqltcl.c: In function ‘Mysqltcl_Connect’:
./generic/mysqltcl.c:914:7: error: unknown type name ‘my_bool’; did you mean ‘_Bool’?
       my_bool reconnect = 1;
       ^~~~~~~
       _Bool
./generic/mysqltcl.c: In function ‘Mysqltcl_Exec’:
./generic/mysqltcl.c:1197:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if ((handle = mysql_prologue(interp, objc, objv, 3, 3, CL_CONN,"handle sql-statement")) == 0)
     ^~
./generic/mysqltcl.c:1201:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  freeResult(handle);
  ^~~~~~~~~~
make: *** [mysqltcl.o] Error 1

A simple fix is to replace my_bool with bool in the generic/mysqltcl.c

**Comment by fayce66** [comment]
I was using an old version of the package on my server (with the same name 3.05), there's no compilation issue with this repository
